package leetcode;

/**
 * Created by Administrator on 2016/11/14.
 * <p>
 * Given two strings s and t which consist of only lowercase letters.

 String t is generated by random shuffling string s and then add one more letter at a random position.

 Find the letter that was added in t.

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.
 */
public class FindTheDifference {

    public static void main(String[] args){
        System.out.println(findTheDifference("","y"));
    }

    public static char findTheDifference(String s, String t) {

        if("".equals(s)){
            return t.charAt(0);
        }

        char[] stochars = s.toCharArray();
        char[] ttochars = t.toCharArray();
        int[][] salphabet = new int[26][1];
        int[][] talphabet = new int[26][1];
        for(char ch : stochars){
            salphabet[ch - 'a'][0] ++;
        }
        for(char ch : ttochars){
            talphabet[ch - 'a'][0] ++;
        }

        for(int i = 0 ; i < ttochars.length ; i++){
            if(salphabet[i][0] != talphabet[i][0]){
                return (char)('a' + i);
            }
        }
        return '1';
    }
}
